In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])

In [3]:
print(a)

[1 2 3 4 5 6]


In [4]:
l=list(a)

In [5]:
l.count(1)

1

In [6]:
a[0]

1

In [7]:
a[2],a[4]

(3, 5)

<h1>Numpy Slicing is Done like list Silicing</h1>

In [8]:
a[1:]

array([2, 3, 4, 5, 6])

In [9]:
a[-1:]

array([6])

In [10]:
a[:-1]

array([1, 2, 3, 4, 5])

In [11]:
type(a)

numpy.ndarray

a.dtype

In [12]:
b=np.array([1.,3.,5.,7])

In [13]:
b.dtype

dtype('float64')

In [14]:
b

array([1., 3., 5., 7.])

In [15]:
a=np.array([1,2,4],dtype=np.int64)

In [16]:
a.dtype

dtype('int64')

In [17]:
a=np.array([1,2,4],dtype=np.int8)

In [18]:
a.dtype

dtype('int8')

In [19]:
c=np.array(["s","h","a","n","n","u"])

In [20]:
c.dtype

dtype('<U1')

In [21]:
d=np.array([{"s":1},{"h":2},{"a":3},{"n":4},{"u":5}])

In [22]:
print(type(d))

<class 'numpy.ndarray'>


In [23]:
e=np.array([[1,2,3],[5,6,7],[8,9,0]])

In [24]:
e

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [25]:
e[0:2]

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
e.shape

(3, 3)

In [27]:
s=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]
])

In [28]:
s[1,0]

4

In [29]:
s[:2,:2]

array([[1, 2],
       [4, 5]])

In [30]:
s[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [31]:
s[:2,2:]

array([[3],
       [6]])

In [32]:
s[:2,1:]

array([[2, 3],
       [5, 6]])

In [33]:
s.sum()

45

In [34]:
s.mean()

5.0

In [35]:
s.std()

2.581988897471611

In [36]:
s.var()

6.666666666666667

In [37]:
s.sum(axis=0)

array([12, 15, 18])

In [38]:
s.sum(axis=1)

array([ 6, 15, 24])

In [39]:
s.mean(axis=1)

array([2., 5., 8.])

In [40]:
s.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [41]:
s.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [42]:
Sys.getsizeof([9])

NameError: name 'Sys' is not defined

In [142]:
b=np.array([[[1,2,3,4],[5,6,7,8]],[[-1,-2,-3,-4],[-5,-6,-7,-8]]])

In [143]:
b.shape

(2, 2, 4)

In [145]:
print(b.shape[0])
print(b.shape[1])
print(b.shape[2])

2
2
4


In [147]:
c=np.array(3)
print(c.ndim)
print(c.nbytes)
print(list(range(5)))

0
4
[0, 1, 2, 3, 4]


In [150]:
A=np.random.permutation(np.arange(19))
A

array([ 7, 17, 14,  2,  3,  0,  6, 13, 12,  9, 16,  5, 11,  4,  1, 15, 10,
       18,  8])

In [152]:
v=np.random.randint(19,42)
v

29

In [164]:
x=np.random.rand(19)*19
c=0
for i in x:
    x[c]=int(i)
    c+=1
x

array([ 3.,  2.,  3., 15.,  6.,  9., 14.,  2., 12.,  0., 12., 14.,  0.,
       18., 16.,  6.,  0., 18.,  3.])

In [166]:
i=np.random.rand(2,3,4,3)
i

array([[[[0.62438548, 0.45107909, 0.22415596],
         [0.35518755, 0.66423787, 0.84990645],
         [0.72526435, 0.71456283, 0.35355017],
         [0.9838325 , 0.17213618, 0.44939659]],

        [[0.31854672, 0.26544544, 0.11176764],
         [0.45039067, 0.60394657, 0.37271146],
         [0.41669515, 0.98964674, 0.32731402],
         [0.9300917 , 0.8041457 , 0.05018461]],

        [[0.30433702, 0.51028294, 0.19796651],
         [0.51992381, 0.21900844, 0.46088878],
         [0.17750091, 0.67787653, 0.22206327],
         [0.66422724, 0.91044561, 0.55584949]]],


       [[[0.29724773, 0.77424809, 0.96683766],
         [0.03822811, 0.6033087 , 0.20428275],
         [0.95300769, 0.3327785 , 0.60777565],
         [0.32223683, 0.0892462 , 0.83480736]],

        [[0.03973358, 0.97464843, 0.39671133],
         [0.7606732 , 0.20923788, 0.2455556 ],
         [0.31932059, 0.99643134, 0.23104577],
         [0.50580196, 0.33369781, 0.71674875]],

        [[0.06091535, 0.29137323, 0.59681872],
 

In [ ]:
n=int(input())
import numpy as np
a=np.arange(n)
for i in range(n):
    a[i]=int(input())
print(a.mean())
if n%2!=0:
    print(a[n/2+1])
else:
    median=a[n/2]+a[n/2+1]
    print(median/2)
max=0
for i in a:
    a.count(i)
    if i>max:
        max=a[i]
print(max)

In [ ]:
n=int(input())
import numpy as np
a=np.arange(n)
for i in range(n):
    a[i]=int(input())
print(a.mean())
if n%2!=0:
    print(a[n/2+1])
else:
    median=a[n/2]+a[n/2+1]
    print(median/2)
max=0
for i in a:
    a.count(i)
    if i>max:
        max=a[i]
print(max)

Broadcasting and vectorized operations

In [43]:
import numpy as np

In [44]:
a=np.arange(5)

In [45]:
a[[True,False,True,False,False]]

array([0, 2])

In [46]:
a*10

array([ 0, 10, 20, 30, 40])

In [47]:
a

array([0, 1, 2, 3, 4])

In [48]:
a+=19

In [49]:
a

array([19, 20, 21, 22, 23])

In [50]:
b=a

In [51]:
b

array([19, 20, 21, 22, 23])

In [52]:
a+b

array([38, 40, 42, 44, 46])

In [53]:
a[(a<=40)&(a!=19)]

array([20, 21, 22, 23])

In [54]:
import sys
import os
import time
a="abcde"
b="aef"
c=0
for i in b:
    if i in a:
      print(i)
    else:
        print("No")
print("Yes")

a
e
No
Yes


In [55]:
np.add(a,b)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U5')) -> dtype('<U5')

In [62]:
a=np.arange(10)
b=np.arange(10,20)
print(np.subtract(a,b))
print(np.multiply(a,b))
np.divide(a,b)
print(np.dot(a,b))

[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171]
735


In [63]:
a.dot(b)

735

In [64]:
a@b


735

In [65]:
#import sys
sys.getsizeof(1)
sys.getsizeof(10**100)

72

In [66]:
sys.getsizeof([1])

64

In [67]:
l=list(range(1000))
n=np.arange(1000)

In [68]:
%time np.sum(n**2)

Wall time: 0 ns


332833500

In [69]:
%time sum(x**2 for x in l)

Wall time: 1 ms


332833500

In [70]:
import pandas as pd
g7_pop=pd.Series({
    "Canada":35.467,
    "France":63.951,
    "Germany":80.948,
    "Italy":127.061,
    "United Kingdom":64.511,
    "United States":318.523
},name="population in millions")

In [71]:
g7_pop

Canada             35.467
France             63.951
Germany            80.948
Italy             127.061
United Kingdom     64.511
United States     318.523
Name: population in millions, dtype: float64

In [72]:
g7_pop.iloc[4]

64.511

In [73]:
g7_pop.iloc[-2]

64.511

In [74]:
g7_pop[["Italy","France"]]

Italy     127.061
France     63.951
Name: population in millions, dtype: float64

In [75]:
g7_pop>70

Canada            False
France            False
Germany            True
Italy              True
United Kingdom    False
United States      True
Name: population in millions, dtype: bool

In [76]:
g7_pop[g7_pop>70]

Germany           80.948
Italy            127.061
United States    318.523
Name: population in millions, dtype: float64

In [78]:
print(g7_pop.mean())
print(g7_pop.std())

115.07683333333334
104.12225520495927


In [80]:
g7_pop.describe()

count      6.000000
mean     115.076833
std      104.122255
min       35.467000
25%       64.091000
50%       72.729500
75%      115.532750
max      318.523000
Name: population in millions, dtype: float64

In [124]:
name=pd.DataFrame({
    "name":["Shannu","Kumar Sai","Someone"],
    "section":["2D","2A","2F"],
    "age":[19,20,21]
})

In [125]:
name

name section  age
0     Shannu      2D   19
1  Kumar Sai      2A   20
2    Someone      2F   21

In [87]:
name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     3 non-null      object
 1   section  3 non-null      object
 2   age      3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [88]:
name.describe()

age
count   3.0
mean   20.0
std     1.0
min    19.0
25%    19.5
50%    20.0
75%    20.5
max    21.0

In [136]:
name.index=[847,588,100,171]

In [91]:
name

name section  age
847     Shannu      2D   19
588  Kumar Sai      2A   20
100    Someone      2F   21

In [93]:
name.dtypes.value_counts()

object    2
int64     1
dtype: int64

In [94]:
name.iloc[-1]

name       Someone
section         2F
age             21
Name: 100, dtype: object

In [99]:
name["age"]

847    19
588    20
100    21
Name: age, dtype: int64

In [102]:
name.loc[847]

name       Shannu
section        2D
age            19
Name: 847, dtype: object

In [105]:
name.loc[:588]

name section  age
847     Shannu      2D   19
588  Kumar Sai      2A   20

In [110]:
name.loc[name["age"]>19,["section"]]

section
588      2A
100      2F

In [126]:
name["branch"]="CSE"

In [112]:
name

name section  age branch
847     Shannu      2D   19    CSE
588  Kumar Sai      2A   20    CSE
100    Someone      2F   21    CSE

In [127]:
name.loc[171]=["Prasad","2A",20,"CSE"]

In [114]:
name

name section  age branch
847     Shannu      2D   19    CSE
588  Kumar Sai      2A   20    CSE
100    Someone      2F   21    CSE
171     Prasad      2A   20    CSE

In [115]:
name.drop(100)

name section  age branch
847     Shannu      2D   19    CSE
588  Kumar Sai      2A   20    CSE
171     Prasad      2A   20    CSE

In [116]:
name

name section  age branch
847     Shannu      2D   19    CSE
588  Kumar Sai      2A   20    CSE
100    Someone      2F   21    CSE
171     Prasad      2A   20    CSE

In [118]:
name.drop(columns=["age"])

name section branch
847     Shannu      2D    CSE
588  Kumar Sai      2A    CSE
100    Someone      2F    CSE
171     Prasad      2A    CSE

In [119]:
name

name section  age branch
847     Shannu      2D   19    CSE
588  Kumar Sai      2A   20    CSE
100    Someone      2F   21    CSE
171     Prasad      2A   20    CSE

In [120]:
name.rename(index={100:332})

name section  age branch
847     Shannu      2D   19    CSE
588  Kumar Sai      2A   20    CSE
332    Someone      2F   21    CSE
171     Prasad      2A   20    CSE

In [129]:
name.loc["name"]="Nagendra"

In [130]:
name.loc["section"]="2E"

In [131]:
name

name   section       age    branch
0           Shannu        2D        19       CSE
1        Kumar Sai        2A        20       CSE
2          Someone        2F        21       CSE
171         Prasad        2A        20       CSE
name      Nagendra  Nagendra  Nagendra  Nagendra
section         2E        2E        2E        2E

In [133]:
name=name.drop(["name","section"])

In [137]:
name

name section age branch
847     Shannu      2D  19    CSE
588  Kumar Sai      2A  20    CSE
100    Someone      2F  21    CSE
171     Prasad      2A  20    CSE

In [138]:
name.loc[100]=["nagendra","2E",19,"CSE"]

In [140]:
name.index=[847,588,332,171]

In [141]:
name

name section age branch
847     Shannu      2D  19    CSE
588  Kumar Sai      2A  20    CSE
332   nagendra      2E  19    CSE
171     Prasad      2A  20    CSE