In [18]:
import numpy

In [2]:
a=numpy.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
l=[19,6,20,2]

In [6]:
b=numpy.array(l)

In [7]:
print(b)

[19  6 20  2]


In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [9]:
w=(19,6,20,2)

In [10]:
c=numpy.array(w)

In [12]:
print(c)

[19  6 20  2]


In [30]:
x=numpy.array([[1,2,3,4],[5,6,7,8]])

In [44]:
x.shape

(2, 4)

In [41]:
x[0:1,1:]

array([[2, 3, 4]])

In [33]:
print(x)
x[1,1]

[[1 2 3 4]
 [5 6 7 8]]


6

In [45]:
x.dtype

dtype('int32')

In [16]:
type(x)

numpy.ndarray

In [19]:
z=numpy.arange(10)

In [20]:
print(z)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
a=numpy.arange(0,100,2)

In [42]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [29]:
a[7]

14

In [35]:
l=[1,2,3,4,5,6,7,8,9]

In [37]:
l[1:5]

[2, 3, 4, 5]

In [43]:
a.shape

(50,)

In [47]:
j=numpy.array([1.3,2,3,4])
print(j)
print(type(j))
print(j.dtype)

[1.3 2.  3.  4. ]
<class 'numpy.ndarray'>
float64


In [48]:
c=numpy.zeros(19)

In [49]:
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
c1=numpy.ones(19)

In [51]:
print(c1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [55]:
c[4]=0.18

In [56]:
c

array([0.  , 0.  , 0.  , 0.  , 0.18, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [59]:
c2=numpy.empty(5)
print(c2)

[5.e-324 5.e-324 0.e+000 0.e+000 0.e+000]


In [ ]:
c3=numpy