In [29]:
import numpy as np
a=np.ones(4,dtype="int8").reshape(2,2)
b=np.ones(9,dtype="int8").reshape(3,3)
c=np.ones(16,dtype="int8").reshape(4,4)

In [30]:
print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [33]:
d=np.identity(2,dtype="int8")
e=np.identity(3,dtype="int8")
f=np.identity(4,dtype="int8")

In [34]:
print(d)
print(e)
print(f)

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
g=np.zeros(10).reshape(2,5)

In [6]:
g

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
h=np.ones(15,dtype="int64").reshape(3,5)

In [8]:
h=h*5

In [9]:
h

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int64)

In [10]:
i=np.random.randint(0,100,25)

In [11]:
i

array([31, 50,  6, 83, 97, 90, 61, 26, 50, 51, 33,  1, 13,  2, 51, 86, 88,
       27, 30, 91, 94, 78, 39, 83, 94])

In [12]:
j=np.random.randint(0,100,6).reshape(2,3)
j
j.resize(3,2)
j

array([[71, 73],
       [ 3, 75],
       [15, 76]])

In [13]:
k=np.random.randint(0,1000,50)

In [14]:
k[0:10]

array([186, 878, 540, 288, 428, 580, 679, 644, 642, 925])

In [15]:
k[-10:]

array([245, 868, 603, 564,  14, 763, 340, 392,  89, 475])

In [16]:
k[10:26]

array([ 68,  31,   8, 993, 470, 800, 851, 852, 694, 466, 409, 364, 346,
       186, 777, 846])

In [17]:
k[22]

346

In [18]:
k[-50:]

array([186, 878, 540, 288, 428, 580, 679, 644, 642, 925,  68,  31,   8,
       993, 470, 800, 851, 852, 694, 466, 409, 364, 346, 186, 777, 846,
       776, 428, 498,  30, 793, 516, 401, 615, 274, 474, 574, 887, 967,
       463, 245, 868, 603, 564,  14, 763, 340, 392,  89, 475])

In [19]:
l=np.array([1,2,3,4,5])
l

array([1, 2, 3, 4, 5])

In [20]:
m=list(l)
m.append(6)
l=np.array(m)
print(l)

[1 2 3 4 5 6]


In [21]:
l=np.insert(l,0,10)
l

array([10,  1,  2,  3,  4,  5,  6])

In [22]:
l=np.insert(l,3,30)
l

array([10,  1,  2, 30,  3,  4,  5,  6])

In [23]:
np.where(l==5)

(array([6], dtype=int64),)

In [24]:
l[6]=50
l

array([10,  1,  2, 30,  3,  4, 50,  6])

In [25]:
l=list(l)
for i in l:
    if i==50:
        l.remove(i)
l=np.array(l)

In [26]:
l

array([10,  1,  2, 30,  3,  4,  6])

In [36]:
m=np.array([[1,2,3],[4,5,6,7]],dtype="object")

In [37]:
m

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [39]:
m[1]

[4, 5, 6, 7]

In [40]:
m.ndim

1

In [41]:
n=np.array([[[1,2,3,4],[5,6,7,8]],[[-1,-2,-3,-4],[-5,-6,-7,-8]]])

In [42]:
n.ndim

3

In [44]:
n.shape

(2, 2, 4)

In [45]:
n.shape[1]

2

In [47]:
n.shape[0]

2

In [50]:
n.shape[2]

4

In [51]:
o=np.array(4)

In [53]:
o.ndim

0

In [54]:
o

array(4)

In [55]:
o.nbytes

4