<b>1.Given two integer numbers return their product only if the product is greater than 1000, else return their sum</b>

In [6]:
a=int(input("Enter an integer:"))
b=int(input("Enter an integer:"))
if (a*b>1000):
    print(a*b)
else:
    print(a+b)

Enter an integer:19
Enter an integer:240
4560


<b>2.Display three string "Data","Science","Python" as "Data ** Science ** Python".Use the print() function to format the given words in the mentioned format.Display the ** seperator between each string.</b>

In [8]:
a="Data"
b="Science"
c="Python"
print("{}**{}**{}".format(a,b,c))

Data**Science**Python


<b>3.Convert Decimal number to octal using print () output formatting.
 Expected Output: The octal number of decimal number 8 is 10</b>


In [9]:
a=int(input("Enter a number:"))
print("octal number of decimal number {} is {}".format(a,oct(a)))

Enter a number:19
octal number of decimal number 19 is 0o23


<b>4.Use a loop to display elements from a given list present at even index positions.</b>

In [11]:
l=[19,0,6,20,2,17,10,25,12]
for i in range(1,len(l),2):
    print(l[i])

0
20
17
25


5. Write a program to print the following start pattern using the for loop

 *
 * * 
 * * *
 * * * * 
 * * * * *
 * * * *
 * * *
 * * 
 *


In [14]:
s=int(input())
for i in range(s):
    for j in range(i+1):
        print("*")

5
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*


In [1]:
"xyz, ABC".capitalize()

'Xyz, abc'

In [2]:
a=[1,2]
a*3



[1, 2, 1, 2, 1, 2]

In [3]:
def with(x,y):

SyntaxError: invalid syntax (<ipython-input-3-8aca74d557a1>, line 1)

In [5]:
print('\\\\')

\\


In [7]:
r=1+"2"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [14]:

math.floor(-3.6)


-4

In [12]:
import math


In [15]:
num=[0,1,2,3]
print(num[::-1])

[3, 2, 1, 0]


In [18]:
x1 = '*Hello*-*Python'
x1.strip("*")

'Hello*-*Python'

In [19]:
type('x=5E10')

str

In [21]:
sorted((5,1,4,2))

[1, 2, 4, 5]

In [22]:
def f1():
    f2()
    print("ln 1")
def f2():
    print("ln 2")
f2(f1())

ln 2
ln 1


TypeError: f2() takes 0 positional arguments but 1 was given

In [24]:
str(int(float("-3.9")))

'-3'

In [26]:
 x1 = 912.3486
print('%.2f'%x1)

912.35


In [28]:
print(max('a', 'A', 'Hello', "z"))

z


In [30]:
print('pythoN prograMMing'.title())

Python Programming


In [31]:
12/4

3.0

In [32]:
12//4

3

In [33]:
age=21
print( age < 23 and (not age < 20))

True


In [35]:
max('Hello World')

'r'

In [37]:
15-5%10

10

In [39]:
-5%10

5

In [43]:
x= 9/3

In [44]:
type(x)

float

In [45]:
'*'.join(['p', 'y', 't', 'h', 'o', 'n'])

'p*y*t*h*o*n'

In [1]:
import numpy as np
a=np.random.randint(19,size=(2,3))

In [2]:
a

array([[ 4,  7, 18],
       [14,  5, 12]])

In [4]:
import sys

In [5]:
sys.getsizeof(1)

28

In [7]:
sys.getsizeof(10**100)

72

In [8]:
sys.getsizeof([1])

64

In [9]:
sys.getsizeof((1,))

48

In [10]:
sys.getsizeof({1})

216

In [11]:
sys.getsizeof(set(1))

TypeError: 'int' object is not iterable

In [1]:
from sklearn.linear_model import LinearRegression
import numpy as np
x=np.array([1,2,3,4,5]).reshape(-1,1)
y=[1,4,9,16,25]
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [2]:
y_predict=model.predict(x)

In [3]:
y_predict

array([-1.,  5., 11., 17., 23.])

In [8]:
x=np.array([8,9,10,11,12]).reshape(-1,1)

In [9]:
y_predict=model.predict(x)

In [10]:
y_predict

array([41., 47., 53., 59., 65.])

In [7]:
x=np.array([1,2,3,4,5]).reshape(-1,1)

In [15]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 2)
poly.fit(x, y)

PolynomialFeatures()

In [16]:
x=np.array([8,9,10,11,12]).reshape(-1,1)

In [19]:
y_predict=poly.predict(x)

AttributeError: 'PolynomialFeatures' object has no attribute 'predict'

In [18]:
y_predict

array([41., 47., 53., 59., 65.])

In [ ]:
lin2.predict(poly.fit_transform(pred2array))